services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment-network

  redis:
    image: redis:7-alpine
    container_name: payment_redis
    ports:
      - "6379:6379"
    networks:
      - payment-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: payment_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS:-guest}
    networks:
      - payment-network

  payment-service:
    build:
      context: ./payments
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@postgres:5432/payment_db
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      PORT: 3002
      NODE_ENV: development
    ports:
      - "3002:3002"
    volumes:
      - ./payment-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - payment-network

volumes:
  postgres_data:

networks:
  payment-network:
    driver: bridge
