services:
  gateway:
    build: ./gateway
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth-service:3000
      - PRODUCT_SERVICE_URL=http://product-service:3000
      - PAYMENT_SERVICE_URL=http://payment-service:3000
    depends_on:
      - auth-service
      - product-service
      - payment-service